### PR TITLE
Rename hasArgs to containsArgs

### PR DESCRIPTION
**Pull request by pkoenig10**
## Before this PR
`LoggableExceptionAssert#hasArgs` only checks whether the given args are contained in the actual args. The name of this method in misleading, as many users probably assume that the method checks that the args are exactly equal. This leads to weaker tests than users may have intended.

This is particularly confusing because [`ServiceExceptionAssert#hasArgs`](ServiceExceptionAssert) has the same name but does check that the args are exactly equal.

## After this PR
`LoggableExceptionAssert#hasArgs` is marked as deprecated in favor of a new method, ``LoggableExceptionAssert#containsArgs`. This should more clearly signal the behavior of this method to users.

This also more closely matches the naming convention of iterables asserts in AssertJ.

### CODE REVIEW

**Comment by dansanduleac** [comment]
Makes sense, would you consider adding a refaster rule as well?
Should be as easy as a new published project `safe-logging-refactorings` with 
```
apply from: "$rootDir/gradle/publish-jar.gradle"
dependencies {
    implementation 'com.google.errorprone:error_prone_refaster'
}
```

**Comment by ferozco** [comment]
👍

**Comment by pkoenig10** [comment]
@ferozco looks like policy-bot didn't accept your approval because you added a merge commit

**Comment by carterkozak** [comment]
👍 (haven't reviewed, but I trust @ferozco :-)

**Comment by pkoenig10** [comment]
Looks like bulldozer isn't working, @ferozco @carterkozak mind merging?

**Pull request merged**
