### PR TITLE
Add utils to render SafeLoggable

### PR DESCRIPTION
**Pull request by rubenfiszel**
Add 3 utils functions to render `SafeLoggable`:

`renderSafeLoggable`: to render a safe loggable with bindings replaced
`renderSafeLoggableWithArgs`: same as above but suffixed by the list of args
`renderArgs`: helper function that now how to render a message given a list of args

The logic can handle a mixed of named  bindings `{named}` and unamed `{}`

### CODE REVIEW

**Comment by iamdanfox** [comment]
@rubenfiszel what's the motivation behind this PR?

**Comment by rubenfiszel** [comment]
@iamdanfox edited the PR description. Code reuse for SafeLoggable rendering. This seems like an utility function that should be part of the lib. We use it across the products of our internal team.

**Comment by JacekLach** [comment]
I thought 'bindings' were discouraged and we weren't supposed to put them in messages anymore? Codex has been removing them pretty much everywhere.

What's the intended rendering of objects/collections in values? `.toString` or json encoded? If json, does this provide any real advantage over just presenting all the params separately to the message?

**Comment by rubenfiszel** [comment]
In our case, it's mostly used to rende args of safe exception. Not sure about the policy for removing bindings. In practice, we still have plenty of bindings and it would be nice for the user to render them correctly.

Maybe the rendering of objects could be improved but I'm of the opinion that instead of special-casing collections, we should pass collections that have a good implementation of toString.

**Comment by iamdanfox** [comment]
I'm actually not 100% sure we want this to live in the same published jar as the SafeLoggable interface.  As a general rule of thumb, shared libraries can be the source of a huge amount of pain (in terms of subtle changes in behaviour, tricky upgrades etc etc), which is kinda the whole reason we push people to share only Conjure API defs.

In this specific case, I'm concerned that the two current known users of this library might end up with slightly diverging requirements and find user-facing behaviour changed as the result of a version bump.  To avoid this problem, would it be feasible to just copy and paste these utilities into the relevant repos?

**Comment by JacekLach** [comment]
>Maybe the rendering of objects could be improved but I'm of the opinion that instead of special-casing collections, we should pass collections that have a good implementation of toString.

Strongly disagree. `.toString` is not reliable, and rarely good user-experience. And now I have to wrap all collections in some toString generating wrappers?

Let's just convert every arg to json instead, which is basically the same as toString for primitives, but way better for objects and collections.


But that's assuming we want to do this at all. Do you have an example of where this kind of interpolation is useful?

**Comment by carterkozak** [comment]
> Let's just convert every arg to json instead, which is basically the same as toString for primitives, but way better for objects and collections.

Converting arbitrary objects to json is incredibly dangerous and should be avoided unless we know the type meant to be json encoded using jackson.

**Comment by iamdanfox** [comment]
I think this is actually unnecessary now that printed exceptions contain the args by default (https://github.com/palantir/safe-logging/pull/77)

**Pull request closed without merging**
